### ISSUE TITLE
Update for macOS Catalina (10.15)

### ISSUE THREAD

**Issue by 4ebyr4ek** [alessandro893/MacOS-WLAN-Driver#13]
Hello!
Will  there be an update for macOS Catalina Beta?

**Comment by alessandro893** [comment]
Hey, only for stable version. It's not ready yet.

**Comment by floxflux** [comment]
cant modify extensions folder in catalina ಥ_ಥ 
csrutil is disabled

**Comment by alessandro893** [comment]
It’s not yet updated for Catalina.

**Comment by alessandro893** [comment]
> cant modify extensions folder in catalina ಥ_ಥ
> csrutil is disabled

It works in Catalina!

Due to new apple's restrictions you need to remount hdd as rw
1. sudo mount -uw /

delete kext via terminal
2.  sudo rm -rf /System/Library/Extensions/IO80211Family.kext

copy kext from 10.14.3 via terminals 'cp' command (from desktop folder in example below)
3. sudo cp -R ~/Desktop/IO80211Family.kext /System/Library/Extensions

4. rebuild caches (or run kextutility.app)

**Comment by floxflux** [comment]
GREAT!! thanks a lot
